### ISSUE TITLE
You can join a player who is red (error)

### ISSUE THREAD

**Issue by fallerOfFalls** [fallerOfFalls/AutismChat4#10]
You're supposed to be able to join a player while you are red, but not be able to join a player who is red.

When you attempt to join a player who is red, you succed, and your name in the server list goes red. But the colour of both your names in chat depends on the `default` colour. If your default colour is white, then both of you will be white in chat, if red then you'll be red in chat.

Dunno what's going on there.

**Comment by RichardB122** [comment]
> But the colour of both your names in chat depends on the default colour. If your default colour is white, then both of you will be white in chat, if red then you'll be red in chat.

This is could be a problem because this is not how I have been implementing it so far. 

Currently your color in the server list and in chat is reflective of the color of the party you are in. When you leave your party or are otherwise alone you switch back to your default color. One issue I see with this is that since you are always whatever color your party is people changing the party's color could affect you.

For example if your party is yellow and everyone was on each other's yellow lists, a member could then switch the party to green. This could mean that all of sudden people could join your party or assimilate your party into another party, even though they weren't on each other's yellow lists.

The two solutions I see for this would either be to have a vote for switching colors, or never let a party be switched to a color that would conflict with another member's default color. Maybe we could change the default color term to be "preferred" color?

**Comment by fallerOfFalls** [comment]
Yes, I'm aware of this potential problem. Everyone in a party has unchecked power to affect everyone. I have imagined players being quite sensitive to this, and asking everyone, before switching the colour of a party. Especially switching from yellow to white or green. So yes, I have imagined a social solution to this, rather than a technical one. However, I don't know exactly how this will play out, so we may need to add something like a vote. But I'd like to try the 'unsafe' version first and see how people handle it. Does that make sense?
