### ISSUE TITLE
Colour is party specific, not player specific

### ISSUE THREAD

**Issue by fallerOfFalls** [fallerOfFalls/AutismChat4#2]
So, when you do a colour operation, (e.g. /green) it changes the colour of the party, and therefore the colour of the usernames of all players you're partied with.

When you join (/join <playername>) a player, you adopt that players party's colour.

When you leave or find yourself otherwise alone (because all other players left the party you were in), you are reset to your default colour.

to set your default colour, use /default <colour>.

Players need another field "defaultColour". and the template can be updated thusly:

```templateForFirstLogin:
  partyID: 0
  defaultColor: WHITE
  globalChat: true
  displayMotd: true
  ```
We don't need `colour` as a field because when a player first logs in they won't be in a party, so they will be their default colour.

**Comment by fallerOfFalls** [comment]
if you do /yellow while in a party, it does the yellow list check for all players against all other players in the party (because all members must be on each other's yellow lists in order to be in a yellow party together). If the check fails, you leave the party instead of changing it to yellow.

/red while in a party makes you automatically leave the party. as in AutismChat 3

**Comment by fallerOfFalls** [comment]
new message:
`you cannot join party <players_in_party> because <list_of_players> aren't on your yellow list.`

hmmm that raises an interesting problem/question. If you are always the same colour as players you're partied with, then you can't join yellow players who aren't on your list. interesting implication, but maybe that's okay.

Or maybe you should be able to join anyway? No, let's try it the consistent way first.

**Comment by RichardB122** [comment]
I've started work on this, but it raises a few questions for me.

So the way I am understanding this is players do not have their own colors anymore at all and that parties are what keep track of colors. I assume you still want player colors to be visible on their names and in the scoreboard and they should just reflect the color of whatever party they are in?

One immediate question I ran into is what should happen if you have a default party set and a default color set that are in conflict? I believe that we discussed removing the default party option, but I can't remember if ever actually decided to actually remove it or not. If we want to keep it and they are in conflict it should probably just make a new party for the new player and set that party to the default color.

Also regarding this: 

"if you do /yellow while in a party, it does the yellow list check for all players against all other players in the party (because all members must be on each other's yellow lists in order to be in a yellow party together). If the check fails, you leave the party instead of changing it to yellow."

I assume you want it to create a new party for the player that is yellow?

**Comment by fallerOfFalls** [comment]
>So the way I am understanding this is players do not have their own colors anymore at all and that parties are what keep track of colors. I assume you still want player colors to be visible on their names and in the scoreboard and they should just reflect the color of whatever party they are in?

yes, exactly!

re: default party, for the purposes of this experiment, the default party feature should be removed as yes you're quite right, it's not compatible. I played with that idea (orienting the design around a default party a few months ago but I could never get thing to make consistent sense, and my current vision for autismchat is very much in a different direction.

>I assume you want it to create a new party for the player that is yellow?

Yes. Just like with AutismChat 3, when you leave a party (e.g. because you turned to yellow).

**Comment by RichardB122** [comment]
I released an initial build which includes almost all of these features with a few exceptions. The default command has not been implemented due to time constraints. I also temporarily disabled the blue color as I did not know how you want it to work in a party setting or if you still wanted to keep it at all.

**Comment by fallerOfFalls** [comment]
okay. good call re /blue. I will probably want to reimplement it, so leave the code in there but disabled till we can see the shape of everything more and can make decisions about how it should behave.

**Comment by fallerOfFalls** [comment]
I think there are some bugs, but it's basically implemented, so I'm gonna close this and open new issues for each bug :)
